FROM node:20-alpine

RUN apk add --no-cache git

WORKDIR /workspace/frontend

COPY frontend/package*.json ./

RUN npm config set registry https://registry.npmmirror.com && \
    npm config set fetch-retries 5 && \
    npm config set fetch-retry-mintimeout 20000 && \
    npm install

COPY frontend/ .

EXPOSE 3000

CMD ["npm", "start"]
